<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/3/17
 * Time: 17:05
 */
namespace App;

use Illuminate\Database\Eloquent\Model;

class Student extends Model{

    //指定数据库表名
    protected $table = 'student';

    //默认是id为主键
    //指定id为主键
    protected $primaryKey = 'id';

    //设置时间戳是否启动 自动维护时间戳
    public $timestamps = true;

    //指定允许批量赋值的字段
    protected $fillable = ['name','age'];

    //时间格式化
    protected function getDateFormat()
    {
        return time(); // TODO: Change the autogenerated stub
    }

    //之间返回$value 取消时间格式化
    protected function asDateTime($value)
    {
        return $value; // TODO: Change the autogenerated stub
    }
}